version: '3.4'

services:
  mac:
    image: mac
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    # Working directory and volume mappings for development
    working_dir: /app
    volumes:
      - ./:/app
